import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import NextAuthSessionProvider from "@/components/SessionProvider";
import Header from "@/components/Header";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="antialiased bg-white text-gray-900 min-h-screen">
        <NextAuthSessionProvider>
          <div className="min-h-screen flex flex-col bg-white">
            <Header />
            {children}
            <footer className="mt-auto py-8 border-t border-gray-50">
              <div className="container mx-auto px-4 text-center">
                <div className="flex justify-center gap-6">
                  <a
                    href="/manual"
                    className="text-[10px] font-black text-gray-300 hover:text-gray-500 transition-colors uppercase tracking-[0.2em]"
                  >
                    Manual
                  </a>
                  <a
                    href="/privacy"
                    className="text-[10px] font-black text-gray-300 hover:text-gray-500 transition-colors uppercase tracking-[0.2em]"
                  >
                    Privacy Policy
                  </a>
                </div>
              </div>
            </footer>
          </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
